### PR TITLE
Fix: Compatibility issue of GitGutter with Snap on Ubuntu

### LINKED ISSUE #495: Snap not working on Ubuntu 18.04
# Support Info

- Sublime Text 3143
- Platform: linux
- Arch: x64
- GitGutter 1.7.14
- Install via PC: True
- git version 2.17.0
- mdpopups 3.3.3
- markdown 2.6.11
- pygments 2.1a0
- jinja2 2.8

## Steps to Reproduce Issue

1. Install GitGutter via snap on Ubuntu 18.04
2. Try to use it

```
GitGutter failed to create git cache: [Errno 2] No such file or directory: '/run/user/1000/snap.sublime-text/GitGutter'
Exception AttributeError: AttributeError("'TempFile' object has no attribute 'name'",) in <bound method TempFile.__del__ of <GitGutter.modules.temp.TempFile object at 0x7facfd3cbb10>> ignored
GitGutter failed to create view cache: [Errno 2] No such file or directory: '/run/user/1000/snap.sublime-text/GitGutter'
Exception AttributeError: AttributeError("'TempFile' object has no attribute 'name'",) in <bound method TempFile.__del__ of <GitGutter.modules.temp.TempFile object at 0x7facfd3cb890>> ignored
Package Control: Skipping automatic upgrade, last run at 2018-05-01 10:20:56, next run at 2018-05-01 11:20:56 or after
```

### PR DESCRIPTION
**Pull request by deathaxe**
Fixes #495 

If Sublime Text is installed via snap package manager on Ubuntu the XDG_RUNTIME_DIR environment variable points to a directory like '/run/user/<pid>/snap.sublime-text/'.

The 'snap.sublime-text' does not exist. Therefore GitGutter fails creating its 'GitGutter' sub directory.

This commit makes use of pythons `os.makedirs()` to ensure the whole path tree is created if required.

Furthermore the `name` and `_mode` attributes are moved to the top of `__init__()` to avoid `AttributeError`s in `__del__()`, if temp-file creation fails.

### CODE REVIEW

File: modules/temp.py [hunk 1]
```diff
@@ -52,26 +52,25 @@ class TempFile(object):
 
     def __init__(self, mode='r'):
         """Initialize TempFile object."""
+        self.name = tempfile.mktemp(dir=TEMP_DIR)
```
Comment (r-stein) [inline modules/temp.py]: Doesn't it result in a an issue to create the temp file before creating the directory?

Comment (deathaxe) [reply modules/temp.py]: `mktemp` does not touch the filesystem in any way. It just creates the path. Using `mkstemp()`  would cause an issue.
