### ISSUE TITLE
Snap not working on Ubuntu 18.04

### ISSUE THREAD

**Issue by ericfrederich** [jisaacks/GitGutter#495]
# Support Info

- Sublime Text 3143
- Platform: linux
- Arch: x64
- GitGutter 1.7.14
- Install via PC: True
- git version 2.17.0
- mdpopups 3.3.3
- markdown 2.6.11
- pygments 2.1a0
- jinja2 2.8

## Steps to Reproduce Issue

1. Install GitGutter via snap on Ubuntu 18.04
2. Try to use it

```
GitGutter failed to create git cache: [Errno 2] No such file or directory: '/run/user/1000/snap.sublime-text/GitGutter'
Exception AttributeError: AttributeError("'TempFile' object has no attribute 'name'",) in <bound method TempFile.__del__ of <GitGutter.modules.temp.TempFile object at 0x7facfd3cbb10>> ignored
GitGutter failed to create view cache: [Errno 2] No such file or directory: '/run/user/1000/snap.sublime-text/GitGutter'
Exception AttributeError: AttributeError("'TempFile' object has no attribute 'name'",) in <bound method TempFile.__del__ of <GitGutter.modules.temp.TempFile object at 0x7facfd3cb890>> ignored
Package Control: Skipping automatic upgrade, last run at 2018-05-01 10:20:56, next run at 2018-05-01 11:20:56 or after
```

**Comment by deathaxe** [comment]
GitGutter queries the `XDG_RUNTIME_DIR` environment variable in the first place to retrieve a user specific temporary folder to put some required temporary files into. If this query returns a string it is assumed or required to point to a valid directory, which is _/run/user/1000/snap.sublime-text)_  in your case.

GitGutter only creates a sub directory `GitGutter` at the moment.

**Comment by ericfrederich** [comment]
Perhaps it should use `os.makedirs` instead of `os.mkdir`

https://stackoverflow.com/a/600612

**Comment by deathaxe** [comment]
Not supported by ST2. Therefore not an option. Would need to walk through the path manually.

**Comment by ericfrederich** [comment]
This didn't make it into the GitHub comment, you just replied via email
perhaps?

**Comment by ericfrederich** [comment]
So I saw @deathaxe said in an email that it isn't supported by ST2 so we'd have to walk path manually.  Don't know what happened to that message.  Maybe he deleted it from this issue or maybe GitHub is bogged down with emails.

So if `os.makedirs` isn't available on ST2 what about using NamedTemporaryFile and not even looking at that environment variable and worrying about weather that path exists or not.

**Comment by r-stein** [comment]
Since ST3 is out of the beta it shouldn't be a big issue to drop ST2 support (as a lot of other packages do). I.e. just create a different branch for ST2 and don't deliver new features for it.

**Comment by deathaxe** [comment]
Please check, whether PR #496 fixes your issue.
